FROM ubuntu
RUN apt-get update && \
    apt-get install -y vim wget python3-pip git
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN /usr/bin/python get-pip.py
RUN rm -rf /var/lib/apt/lists/*